apiVersion: v1
kind: Pod
metadata:
  name: app
  labels: 
    name: app 
spec: 
  containers: 
    - image: mageinferno/magento2-nginx:1.9.9-1
      name: app
      env:
        - name: APP_MAGE_MODE
          value: production
        - name: VIRTUAL_HOST
          value: mysite.com
      ports: 
        - containerPort: 80
          name: app
      volumeMounts:
        - name: app-persistent-storage
          mountPath: /src
  volumes:
    - name: app-persistent-storage
      hostPath:
        path: /tmp/app/src
