apiVersion: v1
kind: Pod
metadata:
  name: db
  labels: 
    name: db 
spec: 
  containers: 
    - image: mariadb:10.0.23 
      name: db
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: magento2
        - name: MYSQL_DATABASE
          value: magento2
        - name: MYSQL_USER
          value: magento2
        - name: MYSQL_PASSWORD
          value: magento2
      ports: 
        - containerPort: 3306
          name: db
      volumeMounts:
        - name: db-persistent-storage
          mountPath: /var/lib/mysql
  volumes:
    - name: db-persistent-storage
      hostPath:
        path: /tmp/db
