apiVersion: v1
kind: ReplicationController
metadata:
  name: db
  labels:
    app: db
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
        tier: backend
    spec:
      containers:
      - name: db
        image: mongo
        ports:
        - containerPort: 27017
