apiVersion: v1
kind: Pod
metadata:
  name: php-fpm
  labels: 
    name: php-fpm 
spec: 
  containers: 
    - image: mageinferno/magento2-php:7.0.1-fpm-2 
      name: php-fpm
      env:
        - name: APP_MAGE_MODE
          value: production
        - name: PHP_MEMORY_LIMIT
          value: 4G
      volumeMounts:
        - name: php-fpm-persistent-storage
          mountPath: /src
  volumes:
    - name: php-fpm-persistent-storage
      hostPath:
        path: /tmp/app/src
